apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-service-app
  labels:
    app: config-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-service-app
  template:
    metadata:
      name: config-service-app
      labels:
        app: config-service-app
    spec:
      containers:
        - name: config-service-app
          image: config-service-img:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9999

---
apiVersion: v1
kind: Service
metadata:
  name: config-service-svc
spec:
  selector:
    app: config-service-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9999
  type: ClusterIP
