apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service-app
  labels:
    app: gateway-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service-app
  template:
    metadata:
      name: gateway-service-app
      labels:
        app: gateway-service-app
    spec:
      containers:
        - name: gateway-service-app
          image: gateway-service-img:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8888

---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service-svc
spec:
  selector:
    app: gateway-service-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8888
  type: LoadBalancer
